name: Audit
on:
  push:
    branches: [jsta]
jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.10"
          enable-cache: true
          cache-dependency-glob: pyproject.toml
      - name: install project
        run: |
          uv sync --all-extras --dev
          uv add pip
      - name: Generate requirements.txt
        run: uv pip compile pyproject.toml -q --no-annotate --universal --group dev -o requirements.txt
      - uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: requirements.txt
          virtual-environment: .venv/
